# -*- coding: utf-8 -*-
"""Marketing Analysis Python for DataScience Ryan Young.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXNR_J3jmnsalnC0uFARnj__1N7RAEzi
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from scipy import stats
import scipy.stats as stats
from datetime import datetime

df=pd.read_csv('/content/marketing_data.csv')
df

df.columns=df.columns.str.strip()
df

df['Income'] = df['Income'].str.replace('$','',regex=False).str.replace(',','',regex=False).astype(float)
df

df.info()

df['Income']=df['Income'].fillna(df.groupby(['Education', 'Marital_Status'])['Income'].transform('median'))
df

df['Total_Children']=df['Kidhome']+df['Teenhome']
df

current_year=datetime.now().year
df['Age']=current_year-df['Year_Birth']
df

df.info()

df.describe()

df['Total_Spending']= df['MntWines']+ df['MntFruits'] + df['MntMeatProducts'] + df['MntFishProducts'] + df['MntSweetProducts'] + df['MntGoldProds']
df

df['Total_Purchases'] = df['NumDealsPurchases'] + df['NumWebPurchases'] + df['NumCatalogPurchases'] + df['NumStorePurchases']
df

plt.boxplot(df['Income'], vert=False)
plt.show()

q1=df['Income'].quantile(0.25)
q3=df['Income'].quantile(0.75)
iqr=q3-q1
upper_bound=q3+1.5*iqr
lower_bound=q1-1.5*iqr
df['Income']=df['Income'].clip(lower=lower_bound, upper=upper_bound)

plt.boxplot(df['Income'], vert=False)
plt.show()

edu_map={'Basic':1, 'Graduation':2, '2n Cycle':2, 'Master':3, 'PhD':4}
df['Education_Rank']=df['Education'].map(edu_map)
df

df_encoded=pd.get_dummies(df, columns=['Marital_Status'], prefix='MS')
df_encoded

marital_map = {
    'Married': 'Partner',
    'Together': 'Partner',
    'Single': 'Alone',
    'Divorced': 'Alone',
    'Widow': 'Alone',
    'Alone': 'Alone',
    'Absurd': 'Alone',
    'YOLO': 'Alone'
}
df['Marital_Group1']=df['Marital_Status'].map(marital_map)
df

df_encoded=pd.get_dummies(df, columns=['Marital_Group1'], prefix='MS')
df_encoded

plt.figure(figsize=(12,8))
sns.heatmap(df.select_dtypes(include=['number']).corr(), annot=True, cmap='Blues', fmt='.1f')
plt.title('Correlation Heatmap of Marketing Variables')
plt.show()

# a. Age vs. Store Shopping
a=stats.pearsonr(df['Age'], df['NumStorePurchases'])
#a=stats.ttest_ind(df['Age'], df['NumStorePurchases'])
print(a)

# b. Children vs. Online Shopping
parents = df[df['Total_Children'] > 0]['NumWebPurchases']
non_parents = df[df['Total_Children'] == 0]['NumWebPurchases']
b=stats.ttest_ind(parents, non_parents)
print(b)

# c. Cannibalization (Correlation Matrix)
Correl_Matrix = df[['NumStorePurchases', 'NumWebPurchases', 'NumCatalogPurchases']].corr()
print(Correl_Matrix)

# d. US vs Rest of World (T-test)
us = df[df['Country'] == 'US']['Total_Purchases']
other_than_us = df[df['Country'] != 'US']['Total_Purchases']
c=stats.ttest_ind(us,other_than_us)
print(c)

a=df.groupby('State')['Sales'].sum().sort_values(ascending=False)
a

mnt_cols= [col for col in df.columns if 'Mnt' in col]
product_sums = df[mnt_cols].sum().sort_values(ascending=False)
plt.figure(figsize=(10,6))
sns.barplot(x=product_sums.index, y=product_sums)
plt.title('Total Sales by Product Category')
plt.xlabel('Product Category')
plt.ylabel('Total Sales')
plt.show()

df_clean = df[df['Age'] < 100]
age_acceptance = df_clean.groupby('Age')['Response'].mean().reset_index()
age_acceptance

plt.figure(figsize=(12, 6))

# sns.regplot handles both the dots and the trend line in one command
sns.regplot(x='Age', y='Response', data=age_acceptance,
            line_kws={"color": "red"}, scatter_kws={"alpha": 0.6})

plt.title('Does Age Affect Campaign Acceptance?', fontsize=16)
plt.xlabel('Customer Age', fontsize=12)
plt.ylabel('Acceptance Rate (0 to 1)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)

plt.show()

country_acceptance = df.groupby('Country')['Response'].sum().reset_index()
country_acceptance

plt.figure(figsize=(10,6))
sns.barplot(data=country_acceptance, x='Country', y='Response')

plt.title('Acceptance Count by Country')
plt.ylabel('Number of Customers (Last Campaign)')
plt.show()

df.describe()

sns.boxplot(x='Total_Children', y='Total_Spending', data=df)
plt.title('Pattern of Total Spending by Number of Children', fontsize=15)
plt.xlabel('Number of Children at Home', fontsize=12)
plt.ylabel('Total Expenditure ($)', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.show()

complaints_df = df[df['Complain'] == 1]
complaints_df

plt.figure(figsize=(10, 6))
sns.countplot(data=complaints_df,
              x='Education',
              order=complaints_df['Education'].value_counts().index)
plt.title('Educational Background of Customers Who Complained', fontsize=15)
plt.xlabel('Education Level', fontsize=12)
plt.ylabel('Number of Complaints', fontsize=12)

plt.show()