# -*- coding: utf-8 -*-
"""Sales Analysis Python for Data Science Ryan Young.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gvsXgTlWfSNZQg4yjyl5yZJxBeJPSI7o
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from scipy import stats

df=pd.read_csv("/content/AusApparalSales4thQrt2020.csv")
df

df.info()

df.isna().sum()

df['Date']=pd.to_datetime(df['Date'], format = '%d-%b-%Y')
df

df.info()

plt.boxplot(x=df['Sales'], vert=False)

sns.histplot(df['Sales'], kde=True)

df['Sales1'] = np.log(df['Sales'])
df

sns.histplot(df['Sales1'], kde=True)

plt.boxplot(df['Sales1'], vert = False)

a=df.groupby('State')['Sales'].sum().sort_values(ascending=False)
a

a.plot(kind='bar')

plt.figure(figsize=(20,8))
sns.barplot(data=df, x='State', y='Sales', hue='Time')
plt.show()

np.mean(df['Sales'])

np.median(df['Sales'])

np.std(df['Sales'])

stats.mode(df['Sales'])

df.describe()

plt.figure(figsize=(12,8))
sns.barplot(data=df, x='Group', y='Sales', errorbar=None)
plt.show()

b=df.groupby('Group')['Sales'].sum().sort_values(ascending=False)
b

df['Month']=df['Date'].dt.to_period('M')
df['Quarter']=df['Date'].dt.to_period('Q')
df['Week']=df['Date'].dt.to_period('W')
df

plt.figure(figsize=(14,7))
c=df.pivot_table(index='Month', columns='Group', values='Sales')
c.plot(kind='bar', figsize=(17,7))
plt.show

c.style.highlight_max(axis=1)

plt.figure(figsize=(14,7))
d=df.pivot_table(index='Quarter', columns='Group', values='Sales')
d.plot(kind='bar', figsize=(17,7))
plt.show()

d.style.highlight_max(axis=1)

plt.figure(figsize=(14,7))
e=df.pivot_table(index='Week', columns='Group', values='Sales')
e.plot(kind='bar', figsize=(17,7))
plt.show()

e.style.highlight_max(axis=1)

print(df.columns)

fig, axes=plt.subplots(2,2,figsize=(20,15))
fig.suptitle('Sales & Marketing Dashboard', fontsize=28)
#1
sns.barplot(ax=axes[0,0], data=df, x='State', y='Sales', hue = 'Group', errorbar=None)
#2
sns.barplot(ax=axes[0,1], data=df, x='Group', y='Sales', hue='State', errorbar=None)
#3
sns.lineplot(ax=axes[1,0], data=df, x='Time', y='Sales', hue='Group', errorbar=None)
#4
sns.lineplot(ax=axes[1,1], data=df, x=df['Date'].astype(str), y='Sales', hue='Time', errorbar=None)

"""Sales Analysis Australia Apparel Sales 4th Quarter 2020
Highest Sales Analysis
The states with the highest sales are Victoria, New South Wales, and South Australia. Victoria and New South Wales are the populous states in the country while South Australia is in the middle of the population distribution by state.
When the sales data is broken down by time it would seem the trend is sales decrease during the day with the greatest number of sales being during the morning. However, in South Australia the sales pick up in the afternoon and fall back down in the evening.
Sales analyzed by kids, men, women, and senior shows the sales are very similar across all categories with men followed by women being responsible for the highest number of sales. If analyzed by only these three states women are the highest spenders. Analysis of these groups over time shows that sales in December coinciding with the Christmas season are highest for all groups. November sales are the lowest while October sales fall in between these two figures. If made more granular there are differences between these groups week to week but there doesn’t seem to be a consistent trend to follow at this granularity.

Lowest Sales Analysis
The three states with the lowest sales are Tasmania, Western Australia, and the Northern Territory. Queensland has comparatively lower sales to the three lowest. While the Northern Territory and Tasmania have very small populations Queensland and Western Australia have the third and fourth largest populations in the country of Australia. Both states populations exceed that of South Australia while their sales are nearly half of those found in South Australia.
To develop a Marketing campaign, we need to look at the trends found within the data from the Sales and Marketing Dashboard. Within Queensland Kids account for the greatest number of sales while in the States with the highest sales the highest spending group is women. Western Australia has its highest spending group as Men. If we are to assume these states would follow the pattern set in Victoria, Queensland, and South Australia a marketing campaign targeting women would be high value. Breaking this down by time women spend less in the morning while increasing spending in afternoon and evening. The total sales are highest in the morning so the marketing campaign should be aware that other key groups will be better targeted in the morning.
Over the fourth Quarter the the greatest sales are in December and a big marketing push during these months could help bring Queensland and Western Australia forward.

"""